package com.intech.player.clean.boundaries.model;

import java.util.List;

/**
 * A response model POJO generated by <a href="http://www.jsonschema2pojo.org">this tool</a>
 * from an <a href=" https://itunes.apple.com/search?term=justin+bieber">ITunes API</a> response.
 *
 * @author Ivan Volnov
 * @since 04.04.18
 */
public class TrackListResponseModel {

    private Integer resultCount;
    private List<TrackResponseModel> results = null;

    public Integer getTrackResponseModelCount() {
        return resultCount;
    }

    public void setTrackResponseModelCount(Integer resultCount) {
        this.resultCount = resultCount;
    }

    public List<TrackResponseModel> getTrackResponseModels() {
        return results;
    }

    public void setTrackResponseModels(List<TrackResponseModel> results) {
        this.results = results;
    }
}


